#!/usr/bin/env python3
"""Regenerate tests/parity_cases.inc from CASES by running every snippet
under the system CPython and capturing its stdout.

Offline dev tool (family convention: CI stays hermetic - the generated
.inc is checked in; re-run via `make parity-cases` after editing CASES
or widening the interpreter subset). Each snippet must stay inside the
ctpy v0.1 subset AND print nothing whose spelling ctpy documents as
divergent (bignum overflow, 17-significant-digit float reprs, set
display order), so that

    static_assert(ctpy::run<SRC>().stdout() == EXPECTED);

pins true CPython parity at compile time.
"""

import pathlib
import subprocess
import sys

CASES = [
    ("arithmetic", """\
print(1 + 2 * 3)
print(7 // 2, 7 % 2, -7 // 2, -7 % 2)
print(2 ** 10, -2 ** 2)
print(7 / 2, 1 / 4)
print(5 - -3, +7, ~7)
"""),
    ("comparisons", """\
print(1 < 2 < 3, 1 < 2 > 3)
print(1 == 1.0, 'a' != 'b')
print(not 0, not [])
print(0 or 'fallback', 1 and 2)
print(3 in [1, 2, 3], 4 not in (1, 2), None is None)
"""),
    ("bitwise", """\
print(6 & 3, 6 | 3, 6 ^ 3)
print(1 << 10, 1024 >> 3)
"""),
    ("loop_sum", """\
total = 0
for i in range(10):
    total += i
print(total)
print(sum(range(100)))
"""),
    ("while_else", """\
n = 5
while n > 0:
    n -= 1
    if n == 2:
        break
else:
    print('exhausted')
print('stopped at', n)
m = 3
while m:
    m -= 1
else:
    print('ran out')
"""),
    ("fib", """\
def fib(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

print(fib(10), fib(20))
"""),
    ("recursion", """\
def fact(n):
    if n <= 1:
        return 1
    return n * fact(n - 1)

print(fact(10))
"""),
    ("defaults", """\
def greet(name, greeting='hello'):
    return greeting + ', ' + name

print(greet('world'))
print(greet('ctpy', 'hi'))
"""),
    ("lists", """\
xs = [3, 1, 4, 1, 5]
xs.append(9)
print(xs)
print(len(xs), xs[0], xs[-1])
print(xs[1:4], xs[::2], xs[::-1])
print(sorted(xs))
print(min(xs), max(xs))
"""),
    ("tuples", """\
a, b = 1, 2
a, b = b, a
print(a, b)
point = (3, 4)
x, y = point
print(x * y, point[0], len(point))
"""),
    ("dicts", """\
d = {'a': 1, 'b': 2}
d['c'] = d['a'] + d['b']
print(d)
print(len(d), 'b' in d, d.get('z', 0))
for k in d:
    print(k, d[k])
for k, v in d.items():
    print(k, '->', v)
print(sorted(d.values()))
"""),
    ("strings", """\
s = 'compile' + '-' + 'time'
print(s, len(s))
print(s[0], s[-4:], s[::-1])
print('py' * 3)
print('i' in s, str(42) + '!')
"""),
    ("fstrings", """\
name = 'world'
n = 7
print(f'hello {name}!')
print(f'{n} squared is {n * n}, and {{braces}} stay')
print(f'nested: {sorted([3, 1, 2])[0]}')
"""),
    ("enumerate_zip", """\
for i, c in enumerate('abc'):
    print(i, c)
for a, b in zip([1, 2, 3], 'xyz'):
    print(a, b)
"""),
    ("grades", """\
for score in (95, 71, 55):
    if score >= 90:
        print(score, 'A')
    elif score >= 70:
        print(score, 'B')
    else:
        print(score, 'F')
"""),
]


def cpp_escape(text: str) -> str:
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        else:
            assert 32 <= ord(ch) < 127, f"non-printable {ch!r} needs escaping"
            out.append(ch)
    return "".join(out)


def literal(text: str, indent: str) -> str:
    """One C string literal per source line, for readable diffs."""
    lines = text.split("\n")
    parts = [line + "\n" for line in lines[:-1]]
    if lines[-1]:
        parts.append(lines[-1])
    if not parts:
        return indent + '""'
    return "\n".join(f'{indent}"{cpp_escape(part)}"' for part in parts)


def main() -> None:
    here = pathlib.Path(__file__).resolve().parent
    chunks = [
        "// GENERATED by tests/gen_expected.py (make parity-cases) - do not edit.\n"
        "// Each expectation is REAL CPython stdout ("
        + f"this run: {sys.version.split()[0]}"
        + "), checked in\n"
        "// so CI never needs a Python; parity.cpp static_asserts ctpy against it.\n"
    ]
    for name, source in CASES:
        result = subprocess.run(
            [sys.executable, "-c", source], capture_output=True, text=True, timeout=30
        )
        if result.returncode != 0:
            sys.exit(f"case {name!r} failed under CPython:\n{result.stderr}")
        chunks.append(
            f"\nPARITY_CASE({name},\n{literal(source, '\t')},\n{literal(result.stdout, '\t')})\n"
        )
    (here / "parity_cases.inc").write_text("".join(chunks))
    print(f"wrote {here / 'parity_cases.inc'} ({len(CASES)} cases)")


if __name__ == "__main__":
    main()
