#include <ctpy.hpp>

// CPython parity, pinned at compile time. tests/parity_cases.inc is
// GENERATED by tests/gen_expected.py (make parity-cases): every case
// pairs a v0.1-subset snippet with the stdout REAL CPython printed for
// it, so each assertion here is "ctpy prints exactly what Python
// prints" - hermetically, since the expectations are checked in.

#define PARITY_CASE(name, src, expected)                                        \
	namespace parity_##name {                                               \
		constexpr auto out = ctpy::run<src>();                          \
		static_assert(out.ok(), "parity " #name ": the script raised"); \
		static_assert(out.stdout() == expected,                         \
		              "parity " #name ": stdout diverges from CPython");\
	}

#include "parity_cases.inc"

#undef PARITY_CASE

int main() { }
