#ifndef CTPY__PYTHON__HPP
#define CTPY__PYTHON__HPP

// THIS FILE WAS GENERATED BY TABLEWRIGHT TOOL, DO NOT MODIFY THIS FILE

#include "../ctll/grammars.hpp"

namespace ctpy {

struct python_grammar {

	// NONTERMINALS:
	struct arg1 {};
	struct arg2 {};
	struct arg3 {};
	struct attr_tail {};
	struct brc1 {};
	struct brc2 {};
	struct brc3 {};
	struct brc4 {};
	struct bval {};
	struct colon_suite {};
	struct def_colon {};
	struct def_gap {};
	struct def_lp {};
	struct def_name {};
	struct dot_attr {};
	struct dq1 {};
	struct dq2 {};
	struct dq_body {};
	struct dtq1 {};
	struct dtq2 {};
	struct dtq_body {};
	struct for_gap {};
	struct for_in1 {};
	struct for_in2 {};
	struct for_t1 {};
	struct for_t2 {};
	struct for_t2_nb {};
	struct for_t3 {};
	struct frac_tail {};
	struct ft_i1 {};
	struct ft_i2 {};
	struct header {};
	struct int_tail {};
	struct ks_b1 {};
	struct ks_b2 {};
	struct ks_b3 {};
	struct ks_b4 {};
	struct ks_b5 {};
	struct ks_c1 {};
	struct ks_c2 {};
	struct ks_c3 {};
	struct ks_c4 {};
	struct ks_c5 {};
	struct ks_c6 {};
	struct ks_c7 {};
	struct ks_c8 {};
	struct ks_cf1 {};
	struct ks_cf2 {};
	struct ks_cf3 {};
	struct ks_cf4 {};
	struct ks_cf5 {};
	struct ks_cn1 {};
	struct ks_cn2 {};
	struct ks_cn3 {};
	struct ks_cn4 {};
	struct ks_ct1 {};
	struct ks_ct2 {};
	struct ks_ct3 {};
	struct ks_ct4 {};
	struct ks_d1 {};
	struct ks_d2 {};
	struct ks_d3 {};
	struct ks_e1 {};
	struct ks_e2 {};
	struct ks_e3f {};
	struct ks_e3s {};
	struct ks_e4f {};
	struct ks_e4s {};
	struct ks_f1 {};
	struct ks_f2 {};
	struct ks_f3 {};
	struct ks_i1 {};
	struct ks_i2 {};
	struct ks_n1 {};
	struct ks_n2 {};
	struct ks_n3 {};
	struct ks_p1 {};
	struct ks_p2 {};
	struct ks_p3 {};
	struct ks_p4 {};
	struct ks_r1 {};
	struct ks_r2 {};
	struct ks_r3 {};
	struct ks_r4 {};
	struct ks_r5 {};
	struct ks_r6 {};
	struct ks_w1 {};
	struct ks_w2 {};
	struct ks_w3 {};
	struct ks_w4 {};
	struct ks_w5 {};
	struct kx_cf1 {};
	struct kx_cf2 {};
	struct kx_cf3 {};
	struct kx_cf4 {};
	struct kx_cf5 {};
	struct kx_cn1 {};
	struct kx_cn2 {};
	struct kx_cn3 {};
	struct kx_cn4 {};
	struct kx_ct1 {};
	struct kx_ct2 {};
	struct kx_ct3 {};
	struct kx_ct4 {};
	struct kx_f1 {};
	struct kx_n1 {};
	struct kx_n2 {};
	struct kx_n3 {};
	struct line_end {};
	struct lst1 {};
	struct lst2 {};
	struct lst3 {};
	struct name_tail {};
	struct opnd {};
	struct opnd_sym {};
	struct par1 {};
	struct par2 {};
	struct par3 {};
	struct prm1 {};
	struct prm2 {};
	struct prm3 {};
	struct prm4 {};
	struct ret_val {};
	struct ret_ws {};
	struct s_amp {};
	struct s_and1 {};
	struct s_and2 {};
	struct s_and3 {};
	struct s_bang {};
	struct s_el1 {};
	struct s_el2 {};
	struct s_el3 {};
	struct s_el4 {};
	struct s_eq {};
	struct s_fdiv {};
	struct s_gt {};
	struct s_hat {};
	struct s_i1 {};
	struct s_if2 {};
	struct s_in2 {};
	struct s_is2 {};
	struct s_lt {};
	struct s_minus {};
	struct s_ni1 {};
	struct s_ni2 {};
	struct s_ni3 {};
	struct s_ni4 {};
	struct s_ni5 {};
	struct s_ni6 {};
	struct s_or1 {};
	struct s_or2 {};
	struct s_pct {};
	struct s_plus {};
	struct s_pow {};
	struct s_shl {};
	struct s_shr {};
	struct s_slash {};
	struct s_star {};
	struct s_vbar {};
	struct scomma {};
	struct sloop {};
	struct sloop_nb {};
	struct sq1 {};
	struct sq2 {};
	struct sq_body {};
	struct start {}; using _start = start;
	struct statement {};
	struct stmt_list {};
	struct stmt_tail {};
	struct stmt_tail_nb {};
	struct sub1 {};
	struct sub2 {};
	struct suite {};
	struct suite_block {};
	struct tq1 {};
	struct tq2 {};
	struct tq_body {};
	struct ws {};
	struct x_and1 {};
	struct x_and2 {};
	struct x_and3 {};
	struct x_bang {};
	struct x_el1 {};
	struct x_el2 {};
	struct x_el3 {};
	struct x_el4 {};
	struct x_eq {};
	struct x_gt {};
	struct x_i1 {};
	struct x_if2 {};
	struct x_in2 {};
	struct x_is2 {};
	struct x_lt {};
	struct x_ni1 {};
	struct x_ni2 {};
	struct x_ni3 {};
	struct x_ni4 {};
	struct x_ni5 {};
	struct x_ni6 {};
	struct x_or1 {};
	struct x_or2 {};
	struct x_slash {};
	struct x_star {};
	struct xloop {};

	// 'action' types:
	struct begin_fstr: ctll::action {};
	struct begin_str: ctll::action {};
	struct begin_suite: ctll::action {};
	struct begin_text: ctll::action {};
	struct bump_line: ctll::action {};
	struct close_block: ctll::action {};
	struct close_brace: ctll::action {};
	struct close_call: ctll::action {};
	struct close_inline: ctll::action {};
	struct close_list: ctll::action {};
	struct close_params: ctll::action {};
	struct close_paren: ctll::action {};
	struct close_sub: ctll::action {};
	struct dict_colon: ctll::action {};
	struct end_module: ctll::action {};
	struct end_stmt: ctll::action {};
	struct end_str: ctll::action {};
	struct for_in: ctll::action {};
	struct kw_break: ctll::action {};
	struct kw_continue: ctll::action {};
	struct kw_def: ctll::action {};
	struct kw_elif: ctll::action {};
	struct kw_else: ctll::action {};
	struct kw_for: ctll::action {};
	struct kw_if: ctll::action {};
	struct kw_pass: ctll::action {};
	struct kw_reject: ctll::action {};
	struct kw_return: ctll::action {};
	struct kw_while: ctll::action {};
	struct mk_assign: ctll::action {};
	struct mk_attr: ctll::action {};
	struct mk_aug: ctll::action {};
	struct mk_false: ctll::action {};
	struct mk_float: ctll::action {};
	struct mk_int: ctll::action {};
	struct mk_kweq: ctll::action {};
	struct mk_name: ctll::action {};
	struct mk_none: ctll::action {};
	struct mk_true: ctll::action {};
	struct op_add: ctll::action {};
	struct op_and: ctll::action {};
	struct op_band: ctll::action {};
	struct op_bor: ctll::action {};
	struct op_bxor: ctll::action {};
	struct op_div: ctll::action {};
	struct op_eq: ctll::action {};
	struct op_fdiv: ctll::action {};
	struct op_ge: ctll::action {};
	struct op_gt: ctll::action {};
	struct op_in: ctll::action {};
	struct op_inv: ctll::action {};
	struct op_is: ctll::action {};
	struct op_le: ctll::action {};
	struct op_lt: ctll::action {};
	struct op_mod: ctll::action {};
	struct op_mul: ctll::action {};
	struct op_ne: ctll::action {};
	struct op_neg: ctll::action {};
	struct op_nin: ctll::action {};
	struct op_not: ctll::action {};
	struct op_or: ctll::action {};
	struct op_pos: ctll::action {};
	struct op_pow: ctll::action {};
	struct op_shl: ctll::action {};
	struct op_shr: ctll::action {};
	struct op_sub: ctll::action {};
	struct open_brace: ctll::action {};
	struct open_call: ctll::action {};
	struct open_list: ctll::action {};
	struct open_params: ctll::action {};
	struct open_paren: ctll::action {};
	struct open_sub: ctll::action {};
	struct push_char: ctll::action {};
	struct push_dq: ctll::action {};
	struct push_sq: ctll::action {};
	struct sep_comma: ctll::action {};
	struct slice_colon: ctll::action {};
	struct tern_else: ctll::action {};
	struct tern_if: ctll::action {};

	// TERMINALS
	using ENDMARK = ctll::term<'\x04'>;
	using set_1 = ctll::set<'\x04','\"','\'','\x28','+','-','0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','~'>;
	using set_2 = ctll::set<'\"','\'','\x28','+','-','0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','~'>;
	using x02__x04 = ctll::set<'\x02','\x04'>;
	using SP = ctll::set<'\x09',' '>;
	using set_3 = ctll::set<'\"','\'','\x28','+','-','0','1','2','3','4','5','6','7','8','9',':','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','~'>;
	using b = ctll::term<'b'>;
	using c = ctll::term<'c'>;
	using d = ctll::term<'d'>;
	using e = ctll::term<'e'>;
	using f = ctll::term<'f'>;
	using i = ctll::term<'i'>;
	using n = ctll::term<'n'>;
	using p = ctll::term<'p'>;
	using r = ctll::term<'r'>;
	using w = ctll::term<'w'>;
	using F = ctll::term<'F'>;
	using N = ctll::term<'N'>;
	using T = ctll::term<'T'>;
	using STMTIDREST = ctll::set<'A','B','C','D','E','G','H','I','J','K','L','M','O','P','Q','R','S','U','V','W','X','Y','Z','_','a','g','h','j','k','l','m','o','q','s','t','u','v','x','y','z'>;
	using DIGIT = ctll::set<'0','1','2','3','4','5','6','7','8','9'>;
	using quote = ctll::term<'\''>;
	using doublequote = ctll::term<'\"'>;
	using open = ctll::term<'\x28'>;
	using sopen = ctll::term<'['>;
	using copen = ctll::term<'\x7B'>;
	using minus = ctll::term<'-'>;
	using plus = ctll::term<'+'>;
	using tilde = ctll::term<'~'>;
	using NEWL = ctll::term<'\x03'>;
	using set_4 = ctll::set<'\x03','\x09',' ','!','%','&','\x28','*','+',',','-','.','/','<','=','>','[','^','a','e','i','n','o','|'>;
	using set_5 = ctll::set<'\x03','\x09',' ','!','%','&','\x28','*','+',',','-','.','/','<','=','>','[','^','|'>;
	using NAMECHAR = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using set_6 = ctll::set<'\x03','\x09',' ','!','%','&','\x28','\x29','*','+',',','-','.','/',':','<','=','>','[',']','^','|','\x7D'>;
	using NCNR = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','s','t','u','v','w','x','y','z'>;
	using NCNE = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using a = ctll::term<'a'>;
	using NCNA = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using k = ctll::term<'k'>;
	using NCNK = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using x03__SP = ctll::set<'\x03','\x09',' '>;
	using o = ctll::term<'o'>;
	using NCNO = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','p','q','r','s','t','u','v','w','x','y','z'>;
	using NCNN = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using t = ctll::term<'t'>;
	using NCNT = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','u','v','w','x','y','z'>;
	using NCNI = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using u = ctll::term<'u'>;
	using NCNU = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','v','w','x','y','z'>;
	using NCNF = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using l = ctll::term<'l'>;
	using NCNL = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using s = ctll::term<'s'>;
	using NCNIS = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','j','k','l','m','n','o','p','q','r','t','u','v','w','x','y','z'>;
	using set_7 = ctll::set<'\x09',' ','\"','\'','\x28','+','-','[','\x7B','~'>;
	using SP__colon = ctll::set<'\x09',' ',':'>;
	using NCNS = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','t','u','v','w','x','y','z'>;
	using set_8 = ctll::set<'\x03','\x09',' ','\"','\'','\x28','+','-','[','\x7B','~'>;
	using doublequote__quote__open__plus__minus__sopen__copen__tilde = ctll::set<'\"','\'','\x28','+','-','[','\x7B','~'>;
	using h = ctll::term<'h'>;
	using NCNH = ctll::set<'0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using colon = ctll::term<':'>;
	using DEDENT = ctll::term<'\x02'>;
	using INDENT = ctll::term<'\x01'>;
	using IDSTART = ctll::set<'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using close = ctll::term<'\x29'>;
	using equal_sign = ctll::term<'='>;
	using comma = ctll::term<','>;
	using IDNOI = ctll::set<'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','_','a','b','c','d','e','f','g','h','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using SP__comma = ctll::set<'\x09',' ',','>;
	using EXPRIDREST = ctll::set<'A','B','C','D','E','G','H','I','J','K','L','M','O','P','Q','R','S','U','V','W','X','Y','Z','_','a','b','c','d','e','g','h','i','j','k','l','m','o','p','q','r','s','t','u','v','w','x','y','z'>;
	using dot = ctll::term<'.'>;
	using set_9 = ctll::set<'\x03','\x09',' ','!','%','&','\x28','\x29','*','+',',','-','/',':','<','=','>','[',']','^','a','e','i','n','o','|','\x7D'>;
	using set_10 = ctll::set<'\x03','\x09',' ','!','%','&','\x28','\x29','*','+',',','-','.','/',':','<','=','>','[',']','^','a','e','i','n','o','|','\x7D'>;
	using star = ctll::term<'*'>;
	using slash = ctll::term<'/'>;
	using percent = ctll::term<'%'>;
	using ampersand = ctll::term<'&'>;
	using pipe = ctll::term<'|'>;
	using caret = ctll::term<'^'>;
	using angle_open = ctll::term<'<'>;
	using angle_close = ctll::term<'>'>;
	using exclamation_mark = ctll::term<'!'>;
	using close__comma__colon__sclose__cclose = ctll::set<'\x29',',',':',']','\x7D'>;
	using set_11 = ctll::set<'\x09',' ','\"','\'','\x28','+','-','0','1','2','3','4','5','6','7','8','9','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','[','_','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','\x7B','~'>;
	using sclose = ctll::term<']'>;
	using cclose = ctll::term<'\x7D'>;
	using ESCANY = ctll::neg_set<'\x00'>;
	using backslash = ctll::term<'\\'>;
	using SQBODY = ctll::neg_set<'\'','\\'>;
	using DQBODY = ctll::neg_set<'\"','\\'>;

	// (q)LL1 function:
	static constexpr auto rule(start, set_1) -> ctll::push<stmt_list, ENDMARK, end_module>;

	static constexpr auto rule(stmt_list, set_2) -> ctll::push<statement, stmt_list>;
	static constexpr auto rule(stmt_list, x02__x04) -> ctll::epsilon;

	static constexpr auto rule(ws, SP) -> ctll::push<ctll::anything, ws>;
	static constexpr auto rule(ws, set_3) -> ctll::epsilon;

	static constexpr auto rule(statement, b) -> ctll::push<ctll::anything, begin_text, push_char, ks_b1>;
	static constexpr auto rule(statement, c) -> ctll::push<ctll::anything, begin_text, push_char, ks_c1>;
	static constexpr auto rule(statement, d) -> ctll::push<ctll::anything, begin_text, push_char, ks_d1>;
	static constexpr auto rule(statement, e) -> ctll::push<ctll::anything, begin_text, push_char, ks_e1>;
	static constexpr auto rule(statement, f) -> ctll::push<ctll::anything, begin_text, push_char, ks_f1>;
	static constexpr auto rule(statement, i) -> ctll::push<ctll::anything, begin_text, push_char, ks_i1>;
	static constexpr auto rule(statement, n) -> ctll::push<ctll::anything, begin_text, push_char, ks_n1>;
	static constexpr auto rule(statement, p) -> ctll::push<ctll::anything, begin_text, push_char, ks_p1>;
	static constexpr auto rule(statement, r) -> ctll::push<ctll::anything, begin_text, push_char, ks_r1>;
	static constexpr auto rule(statement, w) -> ctll::push<ctll::anything, begin_text, push_char, ks_w1>;
	static constexpr auto rule(statement, F) -> ctll::push<ctll::anything, begin_text, push_char, ks_cf1>;
	static constexpr auto rule(statement, N) -> ctll::push<ctll::anything, begin_text, push_char, ks_cn1>;
	static constexpr auto rule(statement, T) -> ctll::push<ctll::anything, begin_text, push_char, ks_ct1>;
	static constexpr auto rule(statement, STMTIDREST) -> ctll::push<ctll::anything, begin_text, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(statement, DIGIT) -> ctll::push<ctll::anything, begin_text, push_char, int_tail, stmt_tail>;
	static constexpr auto rule(statement, quote) -> ctll::push<ctll::anything, begin_str, sq1, stmt_tail>;
	static constexpr auto rule(statement, doublequote) -> ctll::push<ctll::anything, begin_str, dq1, stmt_tail>;
	static constexpr auto rule(statement, open) -> ctll::push<ctll::anything, open_paren, par1, stmt_tail>;
	static constexpr auto rule(statement, sopen) -> ctll::push<ctll::anything, open_list, lst1, stmt_tail>;
	static constexpr auto rule(statement, copen) -> ctll::push<ctll::anything, open_brace, brc1, stmt_tail>;
	static constexpr auto rule(statement, minus) -> ctll::push<ctll::anything, op_neg, ws, opnd, stmt_tail>;
	static constexpr auto rule(statement, plus) -> ctll::push<ctll::anything, op_pos, ws, opnd, stmt_tail>;
	static constexpr auto rule(statement, tilde) -> ctll::push<ctll::anything, op_inv, ws, opnd, stmt_tail>;

	static constexpr auto rule(stmt_tail, set_4) -> ctll::push<sloop, NEWL, end_stmt, bump_line>;

	static constexpr auto rule(stmt_tail_nb, set_5) -> ctll::push<sloop_nb, NEWL, end_stmt, bump_line>;

	static constexpr auto rule(line_end, SP) -> ctll::push<ctll::anything, line_end>;
	static constexpr auto rule(line_end, NEWL) -> ctll::push<ctll::anything, end_stmt, bump_line>;

	static constexpr auto rule(name_tail, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(name_tail, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(ks_b1, r) -> ctll::push<ctll::anything, push_char, ks_b2>;
	static constexpr auto rule(ks_b1, NCNR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_b1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_b2, e) -> ctll::push<ctll::anything, push_char, ks_b3>;
	static constexpr auto rule(ks_b2, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_b2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_b3, a) -> ctll::push<ctll::anything, push_char, ks_b4>;
	static constexpr auto rule(ks_b3, NCNA) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_b3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_b4, k) -> ctll::push<ctll::anything, push_char, ks_b5>;
	static constexpr auto rule(ks_b4, NCNK) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_b4, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_b5, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_b5, x03__SP) -> ctll::push<kw_break, line_end>;

	static constexpr auto rule(ks_c1, o) -> ctll::push<ctll::anything, push_char, ks_c2>;
	static constexpr auto rule(ks_c1, NCNO) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c2, n) -> ctll::push<ctll::anything, push_char, ks_c3>;
	static constexpr auto rule(ks_c2, NCNN) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c3, t) -> ctll::push<ctll::anything, push_char, ks_c4>;
	static constexpr auto rule(ks_c3, NCNT) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c4, i) -> ctll::push<ctll::anything, push_char, ks_c5>;
	static constexpr auto rule(ks_c4, NCNI) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c4, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c5, n) -> ctll::push<ctll::anything, push_char, ks_c6>;
	static constexpr auto rule(ks_c5, NCNN) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c5, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c6, u) -> ctll::push<ctll::anything, push_char, ks_c7>;
	static constexpr auto rule(ks_c6, NCNU) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c6, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c7, e) -> ctll::push<ctll::anything, push_char, ks_c8>;
	static constexpr auto rule(ks_c7, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c7, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_c8, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_c8, x03__SP) -> ctll::push<kw_continue, line_end>;

	static constexpr auto rule(ks_d1, e) -> ctll::push<ctll::anything, push_char, ks_d2>;
	static constexpr auto rule(ks_d1, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_d1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_d2, f) -> ctll::push<ctll::anything, push_char, ks_d3>;
	static constexpr auto rule(ks_d2, NCNF) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_d2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_d3, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_d3, SP) -> ctll::push<kw_def, def_gap>;

	static constexpr auto rule(ks_e1, l) -> ctll::push<ctll::anything, push_char, ks_e2>;
	static constexpr auto rule(ks_e1, NCNL) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_e1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_e2, i) -> ctll::push<ctll::anything, push_char, ks_e3f>;
	static constexpr auto rule(ks_e2, s) -> ctll::push<ctll::anything, push_char, ks_e3s>;
	static constexpr auto rule(ks_e2, NCNIS) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_e2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_e3f, f) -> ctll::push<ctll::anything, push_char, ks_e4f>;
	static constexpr auto rule(ks_e3f, NCNF) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_e3f, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_e4f, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_e4f, set_7) -> ctll::push<kw_elif, header>;

	static constexpr auto rule(ks_e3s, e) -> ctll::push<ctll::anything, push_char, ks_e4s>;
	static constexpr auto rule(ks_e3s, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_e3s, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_e4s, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_e4s, SP__colon) -> ctll::push<kw_else, colon_suite>;

	static constexpr auto rule(ks_f1, o) -> ctll::push<ctll::anything, push_char, ks_f2>;
	static constexpr auto rule(ks_f1, quote) -> ctll::push<ctll::anything, begin_fstr, sq1, stmt_tail>;
	static constexpr auto rule(ks_f1, doublequote) -> ctll::push<ctll::anything, begin_fstr, dq1, stmt_tail>;
	static constexpr auto rule(ks_f1, NCNO) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_f1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_f2, r) -> ctll::push<ctll::anything, push_char, ks_f3>;
	static constexpr auto rule(ks_f2, NCNR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_f2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_f3, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_f3, SP) -> ctll::push<kw_for, for_gap>;

	static constexpr auto rule(ks_i1, f) -> ctll::push<ctll::anything, push_char, ks_i2>;
	static constexpr auto rule(ks_i1, NCNF) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_i1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_i2, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_i2, set_7) -> ctll::push<kw_if, header>;

	static constexpr auto rule(ks_n1, o) -> ctll::push<ctll::anything, push_char, ks_n2>;
	static constexpr auto rule(ks_n1, NCNO) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_n1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_n2, t) -> ctll::push<ctll::anything, push_char, ks_n3>;
	static constexpr auto rule(ks_n2, NCNT) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_n2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_n3, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_n3, set_7) -> ctll::push<op_not, bval, stmt_tail>;

	static constexpr auto rule(ks_p1, a) -> ctll::push<ctll::anything, push_char, ks_p2>;
	static constexpr auto rule(ks_p1, NCNA) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_p1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_p2, s) -> ctll::push<ctll::anything, push_char, ks_p3>;
	static constexpr auto rule(ks_p2, NCNS) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_p2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_p3, s) -> ctll::push<ctll::anything, push_char, ks_p4>;
	static constexpr auto rule(ks_p3, NCNS) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_p3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_p4, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_p4, x03__SP) -> ctll::push<kw_pass, line_end>;

	static constexpr auto rule(ks_r1, e) -> ctll::push<ctll::anything, push_char, ks_r2>;
	static constexpr auto rule(ks_r1, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_r1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_r2, t) -> ctll::push<ctll::anything, push_char, ks_r3>;
	static constexpr auto rule(ks_r2, NCNT) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_r2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_r3, u) -> ctll::push<ctll::anything, push_char, ks_r4>;
	static constexpr auto rule(ks_r3, NCNU) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_r3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_r4, r) -> ctll::push<ctll::anything, push_char, ks_r5>;
	static constexpr auto rule(ks_r4, NCNR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_r4, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_r5, n) -> ctll::push<ctll::anything, push_char, ks_r6>;
	static constexpr auto rule(ks_r5, NCNN) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_r5, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_r6, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_r6, set_8) -> ctll::push<kw_return, ret_val>;

	static constexpr auto rule(ret_val, SP) -> ctll::push<ctll::anything, ret_ws>;
	static constexpr auto rule(ret_val, NEWL) -> ctll::push<ctll::anything, end_stmt, bump_line>;
	static constexpr auto rule(ret_val, doublequote__quote__open__plus__minus__sopen__copen__tilde) -> ctll::push<opnd_sym, stmt_tail>;

	static constexpr auto rule(ret_ws, SP) -> ctll::push<ctll::anything, ret_ws>;
	static constexpr auto rule(ret_ws, NEWL) -> ctll::push<ctll::anything, end_stmt, bump_line>;
	static constexpr auto rule(ret_ws, set_2) -> ctll::push<opnd, stmt_tail>;

	static constexpr auto rule(ks_w1, h) -> ctll::push<ctll::anything, push_char, ks_w2>;
	static constexpr auto rule(ks_w1, NCNH) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_w1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_w2, i) -> ctll::push<ctll::anything, push_char, ks_w3>;
	static constexpr auto rule(ks_w2, NCNI) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_w2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_w3, l) -> ctll::push<ctll::anything, push_char, ks_w4>;
	static constexpr auto rule(ks_w3, NCNL) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_w3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_w4, e) -> ctll::push<ctll::anything, push_char, ks_w5>;
	static constexpr auto rule(ks_w4, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_w4, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_w5, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_w5, set_7) -> ctll::push<kw_while, header>;

	static constexpr auto rule(ks_cf1, a) -> ctll::push<ctll::anything, push_char, ks_cf2>;
	static constexpr auto rule(ks_cf1, NCNA) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cf1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cf2, l) -> ctll::push<ctll::anything, push_char, ks_cf3>;
	static constexpr auto rule(ks_cf2, NCNL) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cf2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cf3, s) -> ctll::push<ctll::anything, push_char, ks_cf4>;
	static constexpr auto rule(ks_cf3, NCNS) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cf3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cf4, e) -> ctll::push<ctll::anything, push_char, ks_cf5>;
	static constexpr auto rule(ks_cf4, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cf4, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cf5, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cf5, set_5) -> ctll::push<mk_false, stmt_tail_nb>;

	static constexpr auto rule(ks_cn1, o) -> ctll::push<ctll::anything, push_char, ks_cn2>;
	static constexpr auto rule(ks_cn1, NCNO) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cn1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cn2, n) -> ctll::push<ctll::anything, push_char, ks_cn3>;
	static constexpr auto rule(ks_cn2, NCNN) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cn2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cn3, e) -> ctll::push<ctll::anything, push_char, ks_cn4>;
	static constexpr auto rule(ks_cn3, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cn3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_cn4, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_cn4, set_5) -> ctll::push<mk_none, stmt_tail_nb>;

	static constexpr auto rule(ks_ct1, r) -> ctll::push<ctll::anything, push_char, ks_ct2>;
	static constexpr auto rule(ks_ct1, NCNR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_ct1, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_ct2, u) -> ctll::push<ctll::anything, push_char, ks_ct3>;
	static constexpr auto rule(ks_ct2, NCNU) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_ct2, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_ct3, e) -> ctll::push<ctll::anything, push_char, ks_ct4>;
	static constexpr auto rule(ks_ct3, NCNE) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_ct3, set_5) -> ctll::push<mk_name, stmt_tail_nb>;

	static constexpr auto rule(ks_ct4, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, stmt_tail>;
	static constexpr auto rule(ks_ct4, set_5) -> ctll::push<mk_true, stmt_tail_nb>;

	static constexpr auto rule(header, set_7) -> ctll::push<bval, xloop, colon, begin_suite, suite>;

	static constexpr auto rule(colon_suite, SP__colon) -> ctll::push<ws, colon, begin_suite, suite>;

	static constexpr auto rule(suite, SP) -> ctll::push<ctll::anything, suite>;
	static constexpr auto rule(suite, NEWL) -> ctll::push<ctll::anything, bump_line, suite_block>;
	static constexpr auto rule(suite, set_2) -> ctll::push<statement, close_inline>;

	static constexpr auto rule(suite_block, INDENT) -> ctll::push<ctll::anything, stmt_list, DEDENT, close_block>;

	static constexpr auto rule(def_gap, SP) -> ctll::push<ctll::anything, def_name>;

	static constexpr auto rule(def_name, SP) -> ctll::push<ctll::anything, def_name>;
	static constexpr auto rule(def_name, IDSTART) -> ctll::push<ctll::anything, begin_text, push_char, name_tail, def_lp>;

	static constexpr auto rule(def_lp, SP) -> ctll::push<ctll::anything, def_lp>;
	static constexpr auto rule(def_lp, open) -> ctll::push<ctll::anything, open_params, prm1>;

	static constexpr auto rule(prm1, SP) -> ctll::push<ctll::anything, prm1>;
	static constexpr auto rule(prm1, close) -> ctll::push<ctll::anything, close_params, def_colon>;
	static constexpr auto rule(prm1, IDSTART) -> ctll::push<ctll::anything, begin_text, push_char, name_tail, prm2>;

	static constexpr auto rule(prm2, SP) -> ctll::push<ctll::anything, prm2>;
	static constexpr auto rule(prm2, equal_sign) -> ctll::push<ctll::anything, mk_kweq, ws, opnd, xloop, prm3>;
	static constexpr auto rule(prm2, comma) -> ctll::push<ctll::anything, sep_comma, prm4>;
	static constexpr auto rule(prm2, close) -> ctll::push<ctll::anything, close_params, def_colon>;

	static constexpr auto rule(prm3, comma) -> ctll::push<ctll::anything, sep_comma, prm4>;
	static constexpr auto rule(prm3, close) -> ctll::push<ctll::anything, close_params, def_colon>;

	static constexpr auto rule(prm4, SP) -> ctll::push<ctll::anything, prm4>;
	static constexpr auto rule(prm4, close) -> ctll::push<ctll::anything, close_params, def_colon>;
	static constexpr auto rule(prm4, IDSTART) -> ctll::push<ctll::anything, begin_text, push_char, name_tail, prm2>;

	static constexpr auto rule(def_colon, SP) -> ctll::push<ctll::anything, def_colon>;
	static constexpr auto rule(def_colon, colon) -> ctll::push<ctll::anything, begin_suite, suite>;

	static constexpr auto rule(for_gap, SP) -> ctll::push<ctll::anything, for_t1>;

	static constexpr auto rule(for_t1, SP) -> ctll::push<ctll::anything, for_t1>;
	static constexpr auto rule(for_t1, IDSTART) -> ctll::push<ctll::anything, begin_text, push_char, name_tail, for_t2>;

	static constexpr auto rule(for_t2, SP) -> ctll::push<ctll::anything, for_t2>;
	static constexpr auto rule(for_t2, comma) -> ctll::push<ctll::anything, sep_comma, for_t3>;
	static constexpr auto rule(for_t2, i) -> ctll::push<ctll::anything, for_in1>;

	static constexpr auto rule(for_in1, n) -> ctll::push<ctll::anything, for_in2>;

	static constexpr auto rule(for_in2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, for_in2>;
	static constexpr auto rule(for_in2, set_7) -> ctll::push<for_in, header>;

	static constexpr auto rule(for_t3, SP) -> ctll::push<ctll::anything, for_t3>;
	static constexpr auto rule(for_t3, i) -> ctll::push<ctll::anything, begin_text, push_char, ft_i1>;
	static constexpr auto rule(for_t3, IDNOI) -> ctll::push<ctll::anything, begin_text, push_char, name_tail, for_t2>;

	static constexpr auto rule(ft_i1, n) -> ctll::push<ctll::anything, push_char, ft_i2>;
	static constexpr auto rule(ft_i1, NCNN) -> ctll::push<ctll::anything, push_char, name_tail, for_t2>;
	static constexpr auto rule(ft_i1, SP__comma) -> ctll::push<mk_name, for_t2_nb>;

	static constexpr auto rule(for_t2_nb, SP) -> ctll::push<ctll::anything, for_t2>;
	static constexpr auto rule(for_t2_nb, comma) -> ctll::push<ctll::anything, sep_comma, for_t3>;

	static constexpr auto rule(ft_i2, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail, for_t2>;
	static constexpr auto rule(ft_i2, set_7) -> ctll::push<for_in, header>;

	static constexpr auto rule(opnd, minus) -> ctll::push<ctll::anything, op_neg, ws, opnd>;
	static constexpr auto rule(opnd, plus) -> ctll::push<ctll::anything, op_pos, ws, opnd>;
	static constexpr auto rule(opnd, tilde) -> ctll::push<ctll::anything, op_inv, ws, opnd>;
	static constexpr auto rule(opnd, DIGIT) -> ctll::push<ctll::anything, begin_text, push_char, int_tail>;
	static constexpr auto rule(opnd, quote) -> ctll::push<ctll::anything, begin_str, sq1>;
	static constexpr auto rule(opnd, doublequote) -> ctll::push<ctll::anything, begin_str, dq1>;
	static constexpr auto rule(opnd, open) -> ctll::push<ctll::anything, open_paren, par1>;
	static constexpr auto rule(opnd, sopen) -> ctll::push<ctll::anything, open_list, lst1>;
	static constexpr auto rule(opnd, copen) -> ctll::push<ctll::anything, open_brace, brc1>;
	static constexpr auto rule(opnd, f) -> ctll::push<ctll::anything, begin_text, push_char, kx_f1>;
	static constexpr auto rule(opnd, n) -> ctll::push<ctll::anything, begin_text, push_char, kx_n1>;
	static constexpr auto rule(opnd, N) -> ctll::push<ctll::anything, begin_text, push_char, kx_cn1>;
	static constexpr auto rule(opnd, T) -> ctll::push<ctll::anything, begin_text, push_char, kx_ct1>;
	static constexpr auto rule(opnd, F) -> ctll::push<ctll::anything, begin_text, push_char, kx_cf1>;
	static constexpr auto rule(opnd, EXPRIDREST) -> ctll::push<ctll::anything, begin_text, push_char, name_tail>;

	static constexpr auto rule(opnd_sym, minus) -> ctll::push<ctll::anything, op_neg, ws, opnd>;
	static constexpr auto rule(opnd_sym, plus) -> ctll::push<ctll::anything, op_pos, ws, opnd>;
	static constexpr auto rule(opnd_sym, tilde) -> ctll::push<ctll::anything, op_inv, ws, opnd>;
	static constexpr auto rule(opnd_sym, quote) -> ctll::push<ctll::anything, begin_str, sq1>;
	static constexpr auto rule(opnd_sym, doublequote) -> ctll::push<ctll::anything, begin_str, dq1>;
	static constexpr auto rule(opnd_sym, open) -> ctll::push<ctll::anything, open_paren, par1>;
	static constexpr auto rule(opnd_sym, sopen) -> ctll::push<ctll::anything, open_list, lst1>;
	static constexpr auto rule(opnd_sym, copen) -> ctll::push<ctll::anything, open_brace, brc1>;

	static constexpr auto rule(bval, SP) -> ctll::push<ctll::anything, ws, opnd>;
	static constexpr auto rule(bval, doublequote__quote__open__plus__minus__sopen__copen__tilde) -> ctll::push<opnd_sym>;

	static constexpr auto rule(kx_f1, quote) -> ctll::push<ctll::anything, begin_fstr, sq1>;
	static constexpr auto rule(kx_f1, doublequote) -> ctll::push<ctll::anything, begin_fstr, dq1>;
	static constexpr auto rule(kx_f1, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_f1, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_n1, o) -> ctll::push<ctll::anything, push_char, kx_n2>;
	static constexpr auto rule(kx_n1, NCNO) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_n1, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_n2, t) -> ctll::push<ctll::anything, push_char, kx_n3>;
	static constexpr auto rule(kx_n2, NCNT) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_n2, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_n3, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_n3, set_7) -> ctll::push<op_not, bval>;

	static constexpr auto rule(kx_cn1, o) -> ctll::push<ctll::anything, push_char, kx_cn2>;
	static constexpr auto rule(kx_cn1, NCNO) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cn1, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cn2, n) -> ctll::push<ctll::anything, push_char, kx_cn3>;
	static constexpr auto rule(kx_cn2, NCNN) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cn2, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cn3, e) -> ctll::push<ctll::anything, push_char, kx_cn4>;
	static constexpr auto rule(kx_cn3, NCNE) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cn3, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cn4, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cn4, set_6) -> ctll::push<mk_none>;

	static constexpr auto rule(kx_ct1, r) -> ctll::push<ctll::anything, push_char, kx_ct2>;
	static constexpr auto rule(kx_ct1, NCNR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_ct1, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_ct2, u) -> ctll::push<ctll::anything, push_char, kx_ct3>;
	static constexpr auto rule(kx_ct2, NCNU) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_ct2, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_ct3, e) -> ctll::push<ctll::anything, push_char, kx_ct4>;
	static constexpr auto rule(kx_ct3, NCNE) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_ct3, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_ct4, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_ct4, set_6) -> ctll::push<mk_true>;

	static constexpr auto rule(kx_cf1, a) -> ctll::push<ctll::anything, push_char, kx_cf2>;
	static constexpr auto rule(kx_cf1, NCNA) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cf1, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cf2, l) -> ctll::push<ctll::anything, push_char, kx_cf3>;
	static constexpr auto rule(kx_cf2, NCNL) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cf2, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cf3, s) -> ctll::push<ctll::anything, push_char, kx_cf4>;
	static constexpr auto rule(kx_cf3, NCNS) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cf3, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cf4, e) -> ctll::push<ctll::anything, push_char, kx_cf5>;
	static constexpr auto rule(kx_cf4, NCNE) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cf4, set_6) -> ctll::push<mk_name>;

	static constexpr auto rule(kx_cf5, NAMECHAR) -> ctll::push<ctll::anything, push_char, name_tail>;
	static constexpr auto rule(kx_cf5, set_6) -> ctll::push<mk_false>;

	static constexpr auto rule(int_tail, DIGIT) -> ctll::push<ctll::anything, push_char, int_tail>;
	static constexpr auto rule(int_tail, dot) -> ctll::push<ctll::anything, push_char, frac_tail>;
	static constexpr auto rule(int_tail, set_9) -> ctll::push<mk_int>;

	static constexpr auto rule(frac_tail, DIGIT) -> ctll::push<ctll::anything, push_char, frac_tail>;
	static constexpr auto rule(frac_tail, set_10) -> ctll::push<mk_float>;

	static constexpr auto rule(xloop, SP) -> ctll::push<ctll::anything, xloop>;
	static constexpr auto rule(xloop, plus) -> ctll::push<ctll::anything, op_add, ws, opnd, xloop>;
	static constexpr auto rule(xloop, minus) -> ctll::push<ctll::anything, op_sub, ws, opnd, xloop>;
	static constexpr auto rule(xloop, star) -> ctll::push<ctll::anything, x_star>;
	static constexpr auto rule(xloop, slash) -> ctll::push<ctll::anything, x_slash>;
	static constexpr auto rule(xloop, percent) -> ctll::push<ctll::anything, op_mod, ws, opnd, xloop>;
	static constexpr auto rule(xloop, ampersand) -> ctll::push<ctll::anything, op_band, ws, opnd, xloop>;
	static constexpr auto rule(xloop, pipe) -> ctll::push<ctll::anything, op_bor, ws, opnd, xloop>;
	static constexpr auto rule(xloop, caret) -> ctll::push<ctll::anything, op_bxor, ws, opnd, xloop>;
	static constexpr auto rule(xloop, angle_open) -> ctll::push<ctll::anything, x_lt>;
	static constexpr auto rule(xloop, angle_close) -> ctll::push<ctll::anything, x_gt>;
	static constexpr auto rule(xloop, exclamation_mark) -> ctll::push<ctll::anything, x_bang>;
	static constexpr auto rule(xloop, equal_sign) -> ctll::push<ctll::anything, x_eq>;
	static constexpr auto rule(xloop, dot) -> ctll::push<ctll::anything, dot_attr, xloop>;
	static constexpr auto rule(xloop, open) -> ctll::push<ctll::anything, open_call, arg1, xloop>;
	static constexpr auto rule(xloop, sopen) -> ctll::push<ctll::anything, open_sub, sub1, xloop>;
	static constexpr auto rule(xloop, o) -> ctll::push<ctll::anything, x_or1>;
	static constexpr auto rule(xloop, a) -> ctll::push<ctll::anything, x_and1>;
	static constexpr auto rule(xloop, i) -> ctll::push<ctll::anything, x_i1>;
	static constexpr auto rule(xloop, n) -> ctll::push<ctll::anything, x_ni1>;
	static constexpr auto rule(xloop, e) -> ctll::push<ctll::anything, x_el1>;
	static constexpr auto rule(xloop, close__comma__colon__sclose__cclose) -> ctll::epsilon;

	static constexpr auto rule(x_star, star) -> ctll::push<ctll::anything, op_pow, ws, opnd, xloop>;
	static constexpr auto rule(x_star, set_11) -> ctll::push<op_mul, ws, opnd, xloop>;

	static constexpr auto rule(x_slash, slash) -> ctll::push<ctll::anything, op_fdiv, ws, opnd, xloop>;
	static constexpr auto rule(x_slash, set_11) -> ctll::push<op_div, ws, opnd, xloop>;

	static constexpr auto rule(x_lt, angle_open) -> ctll::push<ctll::anything, op_shl, ws, opnd, xloop>;
	static constexpr auto rule(x_lt, equal_sign) -> ctll::push<ctll::anything, op_le, ws, opnd, xloop>;
	static constexpr auto rule(x_lt, set_11) -> ctll::push<op_lt, ws, opnd, xloop>;

	static constexpr auto rule(x_gt, angle_close) -> ctll::push<ctll::anything, op_shr, ws, opnd, xloop>;
	static constexpr auto rule(x_gt, equal_sign) -> ctll::push<ctll::anything, op_ge, ws, opnd, xloop>;
	static constexpr auto rule(x_gt, set_11) -> ctll::push<op_gt, ws, opnd, xloop>;

	static constexpr auto rule(x_bang, equal_sign) -> ctll::push<ctll::anything, op_ne, ws, opnd, xloop>;

	static constexpr auto rule(x_eq, equal_sign) -> ctll::push<ctll::anything, op_eq, ws, opnd, xloop>;
	static constexpr auto rule(x_eq, set_11) -> ctll::push<mk_kweq, ws, opnd, xloop>;

	static constexpr auto rule(x_or1, r) -> ctll::push<ctll::anything, x_or2>;

	static constexpr auto rule(x_or2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_or2>;
	static constexpr auto rule(x_or2, set_7) -> ctll::push<op_or, bval, xloop>;

	static constexpr auto rule(x_and1, n) -> ctll::push<ctll::anything, x_and2>;

	static constexpr auto rule(x_and2, d) -> ctll::push<ctll::anything, x_and3>;

	static constexpr auto rule(x_and3, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_and3>;
	static constexpr auto rule(x_and3, set_7) -> ctll::push<op_and, bval, xloop>;

	static constexpr auto rule(x_i1, n) -> ctll::push<ctll::anything, x_in2>;
	static constexpr auto rule(x_i1, f) -> ctll::push<ctll::anything, x_if2>;
	static constexpr auto rule(x_i1, s) -> ctll::push<ctll::anything, x_is2>;

	static constexpr auto rule(x_in2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_in2>;
	static constexpr auto rule(x_in2, set_7) -> ctll::push<op_in, bval, xloop>;

	static constexpr auto rule(x_if2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_if2>;
	static constexpr auto rule(x_if2, set_7) -> ctll::push<tern_if, bval, xloop>;

	static constexpr auto rule(x_is2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_is2>;
	static constexpr auto rule(x_is2, set_7) -> ctll::push<op_is, bval, xloop>;

	static constexpr auto rule(x_ni1, o) -> ctll::push<ctll::anything, x_ni2>;

	static constexpr auto rule(x_ni2, t) -> ctll::push<ctll::anything, x_ni3>;

	static constexpr auto rule(x_ni3, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_ni3>;
	static constexpr auto rule(x_ni3, SP) -> ctll::push<ctll::anything, x_ni4>;

	static constexpr auto rule(x_ni4, SP) -> ctll::push<ctll::anything, x_ni4>;
	static constexpr auto rule(x_ni4, i) -> ctll::push<ctll::anything, x_ni5>;

	static constexpr auto rule(x_ni5, n) -> ctll::push<ctll::anything, x_ni6>;

	static constexpr auto rule(x_ni6, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_ni6>;
	static constexpr auto rule(x_ni6, set_7) -> ctll::push<op_nin, bval, xloop>;

	static constexpr auto rule(x_el1, l) -> ctll::push<ctll::anything, x_el2>;

	static constexpr auto rule(x_el2, s) -> ctll::push<ctll::anything, x_el3>;

	static constexpr auto rule(x_el3, e) -> ctll::push<ctll::anything, x_el4>;

	static constexpr auto rule(x_el4, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, x_el4>;
	static constexpr auto rule(x_el4, set_7) -> ctll::push<tern_else, bval, xloop>;

	static constexpr auto rule(dot_attr, SP) -> ctll::push<ctll::anything, dot_attr>;
	static constexpr auto rule(dot_attr, IDSTART) -> ctll::push<ctll::anything, begin_text, push_char, attr_tail>;

	static constexpr auto rule(attr_tail, NAMECHAR) -> ctll::push<ctll::anything, push_char, attr_tail>;
	static constexpr auto rule(attr_tail, set_6) -> ctll::push<mk_attr>;

	static constexpr auto rule(sloop, SP) -> ctll::push<ctll::anything, sloop>;
	static constexpr auto rule(sloop, comma) -> ctll::push<ctll::anything, sep_comma, scomma>;
	static constexpr auto rule(sloop, plus) -> ctll::push<ctll::anything, s_plus>;
	static constexpr auto rule(sloop, minus) -> ctll::push<ctll::anything, s_minus>;
	static constexpr auto rule(sloop, star) -> ctll::push<ctll::anything, s_star>;
	static constexpr auto rule(sloop, slash) -> ctll::push<ctll::anything, s_slash>;
	static constexpr auto rule(sloop, percent) -> ctll::push<ctll::anything, s_pct>;
	static constexpr auto rule(sloop, ampersand) -> ctll::push<ctll::anything, s_amp>;
	static constexpr auto rule(sloop, pipe) -> ctll::push<ctll::anything, s_vbar>;
	static constexpr auto rule(sloop, caret) -> ctll::push<ctll::anything, s_hat>;
	static constexpr auto rule(sloop, angle_open) -> ctll::push<ctll::anything, s_lt>;
	static constexpr auto rule(sloop, angle_close) -> ctll::push<ctll::anything, s_gt>;
	static constexpr auto rule(sloop, exclamation_mark) -> ctll::push<ctll::anything, s_bang>;
	static constexpr auto rule(sloop, equal_sign) -> ctll::push<ctll::anything, s_eq>;
	static constexpr auto rule(sloop, dot) -> ctll::push<ctll::anything, dot_attr, sloop>;
	static constexpr auto rule(sloop, open) -> ctll::push<ctll::anything, open_call, arg1, sloop>;
	static constexpr auto rule(sloop, sopen) -> ctll::push<ctll::anything, open_sub, sub1, sloop>;
	static constexpr auto rule(sloop, o) -> ctll::push<ctll::anything, s_or1>;
	static constexpr auto rule(sloop, a) -> ctll::push<ctll::anything, s_and1>;
	static constexpr auto rule(sloop, i) -> ctll::push<ctll::anything, s_i1>;
	static constexpr auto rule(sloop, n) -> ctll::push<ctll::anything, s_ni1>;
	static constexpr auto rule(sloop, e) -> ctll::push<ctll::anything, s_el1>;
	static constexpr auto rule(sloop, NEWL) -> ctll::epsilon;

	static constexpr auto rule(sloop_nb, SP) -> ctll::push<ctll::anything, sloop>;
	static constexpr auto rule(sloop_nb, comma) -> ctll::push<ctll::anything, sep_comma, scomma>;
	static constexpr auto rule(sloop_nb, plus) -> ctll::push<ctll::anything, s_plus>;
	static constexpr auto rule(sloop_nb, minus) -> ctll::push<ctll::anything, s_minus>;
	static constexpr auto rule(sloop_nb, star) -> ctll::push<ctll::anything, s_star>;
	static constexpr auto rule(sloop_nb, slash) -> ctll::push<ctll::anything, s_slash>;
	static constexpr auto rule(sloop_nb, percent) -> ctll::push<ctll::anything, s_pct>;
	static constexpr auto rule(sloop_nb, ampersand) -> ctll::push<ctll::anything, s_amp>;
	static constexpr auto rule(sloop_nb, pipe) -> ctll::push<ctll::anything, s_vbar>;
	static constexpr auto rule(sloop_nb, caret) -> ctll::push<ctll::anything, s_hat>;
	static constexpr auto rule(sloop_nb, angle_open) -> ctll::push<ctll::anything, s_lt>;
	static constexpr auto rule(sloop_nb, angle_close) -> ctll::push<ctll::anything, s_gt>;
	static constexpr auto rule(sloop_nb, exclamation_mark) -> ctll::push<ctll::anything, s_bang>;
	static constexpr auto rule(sloop_nb, equal_sign) -> ctll::push<ctll::anything, s_eq>;
	static constexpr auto rule(sloop_nb, dot) -> ctll::push<ctll::anything, dot_attr, sloop>;
	static constexpr auto rule(sloop_nb, open) -> ctll::push<ctll::anything, open_call, arg1, sloop>;
	static constexpr auto rule(sloop_nb, sopen) -> ctll::push<ctll::anything, open_sub, sub1, sloop>;
	static constexpr auto rule(sloop_nb, NEWL) -> ctll::epsilon;

	static constexpr auto rule(scomma, SP) -> ctll::push<ctll::anything, scomma>;
	static constexpr auto rule(scomma, equal_sign) -> ctll::push<ctll::anything, mk_assign, ws, opnd, sloop>;
	static constexpr auto rule(scomma, set_2) -> ctll::push<opnd, sloop>;
	static constexpr auto rule(scomma, NEWL) -> ctll::epsilon;

	static constexpr auto rule(s_plus, equal_sign) -> ctll::push<ctll::anything, op_add, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_plus, set_11) -> ctll::push<op_add, ws, opnd, sloop>;

	static constexpr auto rule(s_minus, equal_sign) -> ctll::push<ctll::anything, op_sub, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_minus, set_11) -> ctll::push<op_sub, ws, opnd, sloop>;

	static constexpr auto rule(s_star, star) -> ctll::push<ctll::anything, s_pow>;
	static constexpr auto rule(s_star, equal_sign) -> ctll::push<ctll::anything, op_mul, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_star, set_11) -> ctll::push<op_mul, ws, opnd, sloop>;

	static constexpr auto rule(s_pow, equal_sign) -> ctll::push<ctll::anything, op_pow, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_pow, set_11) -> ctll::push<op_pow, ws, opnd, sloop>;

	static constexpr auto rule(s_slash, slash) -> ctll::push<ctll::anything, s_fdiv>;
	static constexpr auto rule(s_slash, equal_sign) -> ctll::push<ctll::anything, op_div, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_slash, set_11) -> ctll::push<op_div, ws, opnd, sloop>;

	static constexpr auto rule(s_fdiv, equal_sign) -> ctll::push<ctll::anything, op_fdiv, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_fdiv, set_11) -> ctll::push<op_fdiv, ws, opnd, sloop>;

	static constexpr auto rule(s_pct, equal_sign) -> ctll::push<ctll::anything, op_mod, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_pct, set_11) -> ctll::push<op_mod, ws, opnd, sloop>;

	static constexpr auto rule(s_amp, equal_sign) -> ctll::push<ctll::anything, op_band, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_amp, set_11) -> ctll::push<op_band, ws, opnd, sloop>;

	static constexpr auto rule(s_vbar, equal_sign) -> ctll::push<ctll::anything, op_bor, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_vbar, set_11) -> ctll::push<op_bor, ws, opnd, sloop>;

	static constexpr auto rule(s_hat, equal_sign) -> ctll::push<ctll::anything, op_bxor, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_hat, set_11) -> ctll::push<op_bxor, ws, opnd, sloop>;

	static constexpr auto rule(s_lt, angle_open) -> ctll::push<ctll::anything, s_shl>;
	static constexpr auto rule(s_lt, equal_sign) -> ctll::push<ctll::anything, op_le, ws, opnd, sloop>;
	static constexpr auto rule(s_lt, set_11) -> ctll::push<op_lt, ws, opnd, sloop>;

	static constexpr auto rule(s_shl, equal_sign) -> ctll::push<ctll::anything, op_shl, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_shl, set_11) -> ctll::push<op_shl, ws, opnd, sloop>;

	static constexpr auto rule(s_gt, angle_close) -> ctll::push<ctll::anything, s_shr>;
	static constexpr auto rule(s_gt, equal_sign) -> ctll::push<ctll::anything, op_ge, ws, opnd, sloop>;
	static constexpr auto rule(s_gt, set_11) -> ctll::push<op_gt, ws, opnd, sloop>;

	static constexpr auto rule(s_shr, equal_sign) -> ctll::push<ctll::anything, op_shr, mk_aug, ws, opnd, sloop>;
	static constexpr auto rule(s_shr, set_11) -> ctll::push<op_shr, ws, opnd, sloop>;

	static constexpr auto rule(s_bang, equal_sign) -> ctll::push<ctll::anything, op_ne, ws, opnd, sloop>;

	static constexpr auto rule(s_eq, equal_sign) -> ctll::push<ctll::anything, op_eq, ws, opnd, sloop>;
	static constexpr auto rule(s_eq, set_11) -> ctll::push<mk_assign, ws, opnd, sloop>;

	static constexpr auto rule(s_or1, r) -> ctll::push<ctll::anything, s_or2>;

	static constexpr auto rule(s_or2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_or2>;
	static constexpr auto rule(s_or2, set_7) -> ctll::push<op_or, bval, sloop>;

	static constexpr auto rule(s_and1, n) -> ctll::push<ctll::anything, s_and2>;

	static constexpr auto rule(s_and2, d) -> ctll::push<ctll::anything, s_and3>;

	static constexpr auto rule(s_and3, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_and3>;
	static constexpr auto rule(s_and3, set_7) -> ctll::push<op_and, bval, sloop>;

	static constexpr auto rule(s_i1, n) -> ctll::push<ctll::anything, s_in2>;
	static constexpr auto rule(s_i1, f) -> ctll::push<ctll::anything, s_if2>;
	static constexpr auto rule(s_i1, s) -> ctll::push<ctll::anything, s_is2>;

	static constexpr auto rule(s_in2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_in2>;
	static constexpr auto rule(s_in2, set_7) -> ctll::push<op_in, bval, sloop>;

	static constexpr auto rule(s_if2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_if2>;
	static constexpr auto rule(s_if2, set_7) -> ctll::push<tern_if, bval, sloop>;

	static constexpr auto rule(s_is2, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_is2>;
	static constexpr auto rule(s_is2, set_7) -> ctll::push<op_is, bval, sloop>;

	static constexpr auto rule(s_ni1, o) -> ctll::push<ctll::anything, s_ni2>;

	static constexpr auto rule(s_ni2, t) -> ctll::push<ctll::anything, s_ni3>;

	static constexpr auto rule(s_ni3, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_ni3>;
	static constexpr auto rule(s_ni3, SP) -> ctll::push<ctll::anything, s_ni4>;

	static constexpr auto rule(s_ni4, SP) -> ctll::push<ctll::anything, s_ni4>;
	static constexpr auto rule(s_ni4, i) -> ctll::push<ctll::anything, s_ni5>;

	static constexpr auto rule(s_ni5, n) -> ctll::push<ctll::anything, s_ni6>;

	static constexpr auto rule(s_ni6, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_ni6>;
	static constexpr auto rule(s_ni6, set_7) -> ctll::push<op_nin, bval, sloop>;

	static constexpr auto rule(s_el1, l) -> ctll::push<ctll::anything, s_el2>;

	static constexpr auto rule(s_el2, s) -> ctll::push<ctll::anything, s_el3>;

	static constexpr auto rule(s_el3, e) -> ctll::push<ctll::anything, s_el4>;

	static constexpr auto rule(s_el4, NAMECHAR) -> ctll::push<ctll::anything, kw_reject, s_el4>;
	static constexpr auto rule(s_el4, set_7) -> ctll::push<tern_else, bval, sloop>;

	static constexpr auto rule(par1, SP) -> ctll::push<ctll::anything, par1>;
	static constexpr auto rule(par1, close) -> ctll::push<ctll::anything, close_paren>;
	static constexpr auto rule(par1, set_2) -> ctll::push<opnd, xloop, par2>;

	static constexpr auto rule(par2, comma) -> ctll::push<ctll::anything, sep_comma, par3>;
	static constexpr auto rule(par2, close) -> ctll::push<ctll::anything, close_paren>;

	static constexpr auto rule(par3, SP) -> ctll::push<ctll::anything, par3>;
	static constexpr auto rule(par3, close) -> ctll::push<ctll::anything, close_paren>;
	static constexpr auto rule(par3, set_2) -> ctll::push<opnd, xloop, par2>;

	static constexpr auto rule(lst1, SP) -> ctll::push<ctll::anything, lst1>;
	static constexpr auto rule(lst1, sclose) -> ctll::push<ctll::anything, close_list>;
	static constexpr auto rule(lst1, set_2) -> ctll::push<opnd, xloop, lst2>;

	static constexpr auto rule(lst2, comma) -> ctll::push<ctll::anything, sep_comma, lst3>;
	static constexpr auto rule(lst2, sclose) -> ctll::push<ctll::anything, close_list>;

	static constexpr auto rule(lst3, SP) -> ctll::push<ctll::anything, lst3>;
	static constexpr auto rule(lst3, sclose) -> ctll::push<ctll::anything, close_list>;
	static constexpr auto rule(lst3, set_2) -> ctll::push<opnd, xloop, lst2>;

	static constexpr auto rule(brc1, SP) -> ctll::push<ctll::anything, brc1>;
	static constexpr auto rule(brc1, cclose) -> ctll::push<ctll::anything, close_brace>;
	static constexpr auto rule(brc1, set_2) -> ctll::push<opnd, xloop, brc2>;

	static constexpr auto rule(brc2, colon) -> ctll::push<ctll::anything, dict_colon, ws, opnd, xloop, brc3>;
	static constexpr auto rule(brc2, comma) -> ctll::push<ctll::anything, sep_comma, brc4>;
	static constexpr auto rule(brc2, cclose) -> ctll::push<ctll::anything, close_brace>;

	static constexpr auto rule(brc3, comma) -> ctll::push<ctll::anything, sep_comma, brc4>;
	static constexpr auto rule(brc3, cclose) -> ctll::push<ctll::anything, close_brace>;

	static constexpr auto rule(brc4, SP) -> ctll::push<ctll::anything, brc4>;
	static constexpr auto rule(brc4, cclose) -> ctll::push<ctll::anything, close_brace>;
	static constexpr auto rule(brc4, set_2) -> ctll::push<opnd, xloop, brc2>;

	static constexpr auto rule(arg1, SP) -> ctll::push<ctll::anything, arg1>;
	static constexpr auto rule(arg1, close) -> ctll::push<ctll::anything, close_call>;
	static constexpr auto rule(arg1, set_2) -> ctll::push<opnd, xloop, arg2>;

	static constexpr auto rule(arg2, comma) -> ctll::push<ctll::anything, sep_comma, arg3>;
	static constexpr auto rule(arg2, close) -> ctll::push<ctll::anything, close_call>;

	static constexpr auto rule(arg3, SP) -> ctll::push<ctll::anything, arg3>;
	static constexpr auto rule(arg3, close) -> ctll::push<ctll::anything, close_call>;
	static constexpr auto rule(arg3, set_2) -> ctll::push<opnd, xloop, arg2>;

	static constexpr auto rule(sub1, SP) -> ctll::push<ctll::anything, sub1>;
	static constexpr auto rule(sub1, colon) -> ctll::push<ctll::anything, slice_colon, sub1>;
	static constexpr auto rule(sub1, sclose) -> ctll::push<ctll::anything, close_sub>;
	static constexpr auto rule(sub1, set_2) -> ctll::push<opnd, xloop, sub2>;

	static constexpr auto rule(sub2, colon) -> ctll::push<ctll::anything, slice_colon, sub1>;
	static constexpr auto rule(sub2, sclose) -> ctll::push<ctll::anything, close_sub>;

	static constexpr auto rule(sq1, quote) -> ctll::push<ctll::anything, sq2>;
	static constexpr auto rule(sq1, backslash) -> ctll::push<ctll::anything, push_char, ESCANY, push_char, sq_body>;
	static constexpr auto rule(sq1, SQBODY) -> ctll::push<ctll::anything, push_char, sq_body>;

	static constexpr auto rule(sq_body, quote) -> ctll::push<ctll::anything, end_str>;
	static constexpr auto rule(sq_body, backslash) -> ctll::push<ctll::anything, push_char, ESCANY, push_char, sq_body>;
	static constexpr auto rule(sq_body, SQBODY) -> ctll::push<ctll::anything, push_char, sq_body>;

	static constexpr auto rule(sq2, quote) -> ctll::push<ctll::anything, tq_body>;
	static constexpr auto rule(sq2, set_10) -> ctll::push<end_str>;

	static constexpr auto rule(tq_body, quote) -> ctll::push<ctll::anything, tq1>;
	static constexpr auto rule(tq_body, backslash) -> ctll::push<ctll::anything, push_char, ESCANY, push_char, tq_body>;
	static constexpr auto rule(tq_body, SQBODY) -> ctll::push<ctll::anything, push_char, tq_body>;

	static constexpr auto rule(tq1, quote) -> ctll::push<ctll::anything, tq2>;
	static constexpr auto rule(tq1, backslash) -> ctll::push<ctll::anything, push_sq, push_char, ESCANY, push_char, tq_body>;
	static constexpr auto rule(tq1, SQBODY) -> ctll::push<ctll::anything, push_sq, push_char, tq_body>;

	static constexpr auto rule(tq2, quote) -> ctll::push<ctll::anything, end_str>;
	static constexpr auto rule(tq2, backslash) -> ctll::push<ctll::anything, push_sq, push_sq, push_char, ESCANY, push_char, tq_body>;
	static constexpr auto rule(tq2, SQBODY) -> ctll::push<ctll::anything, push_sq, push_sq, push_char, tq_body>;

	static constexpr auto rule(dq1, doublequote) -> ctll::push<ctll::anything, dq2>;
	static constexpr auto rule(dq1, backslash) -> ctll::push<ctll::anything, push_char, ESCANY, push_char, dq_body>;
	static constexpr auto rule(dq1, DQBODY) -> ctll::push<ctll::anything, push_char, dq_body>;

	static constexpr auto rule(dq_body, doublequote) -> ctll::push<ctll::anything, end_str>;
	static constexpr auto rule(dq_body, backslash) -> ctll::push<ctll::anything, push_char, ESCANY, push_char, dq_body>;
	static constexpr auto rule(dq_body, DQBODY) -> ctll::push<ctll::anything, push_char, dq_body>;

	static constexpr auto rule(dq2, doublequote) -> ctll::push<ctll::anything, dtq_body>;
	static constexpr auto rule(dq2, set_10) -> ctll::push<end_str>;

	static constexpr auto rule(dtq_body, doublequote) -> ctll::push<ctll::anything, dtq1>;
	static constexpr auto rule(dtq_body, backslash) -> ctll::push<ctll::anything, push_char, ESCANY, push_char, dtq_body>;
	static constexpr auto rule(dtq_body, DQBODY) -> ctll::push<ctll::anything, push_char, dtq_body>;

	static constexpr auto rule(dtq1, doublequote) -> ctll::push<ctll::anything, dtq2>;
	static constexpr auto rule(dtq1, backslash) -> ctll::push<ctll::anything, push_dq, push_char, ESCANY, push_char, dtq_body>;
	static constexpr auto rule(dtq1, DQBODY) -> ctll::push<ctll::anything, push_dq, push_char, dtq_body>;

	static constexpr auto rule(dtq2, doublequote) -> ctll::push<ctll::anything, end_str>;
	static constexpr auto rule(dtq2, backslash) -> ctll::push<ctll::anything, push_dq, push_dq, push_char, ESCANY, push_char, dtq_body>;
	static constexpr auto rule(dtq2, DQBODY) -> ctll::push<ctll::anything, push_dq, push_dq, push_char, dtq_body>;

};

}

#endif //CTPY__PYTHON__HPP
